// CPU ID declarations  generated by parsecpuids.py  Apr 16, 2015  15:58:35

// don't modify this file. Make changes to cpuids.txt and regenerate
#define HOST 0x0 	// 
#define ME 0x0 	// 
#define YOU 0x0 	// 
#define DIRECT 0x0 	// 
#define MAIN_CPU 0x1 	// 
#define MAIN_HOST 0x2 	// host ports on cpus
#define ROUTING_POINTS 0x3 	// number of points for routing
unsigned char whoami(void);