// CPU ID declarations  generated by parsecpuids.py  Jan 17, 2017  16:59:55

// don't modify this file. Make changes to cpuids.txt and regenerate
#ifndef _WHO_H_
#define _WHO_H_
#define HOST 0x0 	// 
#define ME 0x0 	// 
#define YOU 0x0 	// 
#define DIRECT 0x0 	// 
#define MAIN_CPU 0x1 	// 
#define MAIN_HOST 0x2 	// host ports on cpus
#define ROUTING_POINTS 0x3 	// number of points for routing
#endif

unsigned char whoami(void);