// CPU ID declarations  generated by parsecpuids.py  Sep 28, 2012  16:25:35

// don't modify this file. Make changes to cpuids.txt and regenerate
#define HOST 0x0 	// 
#define ME 0x0 	// 
#define YOU 0x0 	// 
#define DIRECT 0x0 	// 
#define MAIN_CPU 0x1 	// 
#define DISPLAY_CPU 0x2 	// 
#define SLOTA_CPU 0x3 	// 
#define SLOTB_CPU 0x4 	// 
#define MAIN_HOST 0x5 	// host ports on cpus
#define DISPLAY_HOST 0x6 	// 
#define SLOTA_HOST 0x7 	// 
#define SLOTB_HOST 0x8 	// 
#define ROUTING_POINTS 0x9 	// number of points for routing
unsigned char whoami(void);