// CPU ID declarations  generated by parsecpuids.py  Jun 11, 2015  17:34:37

// don't modify this file. Make changes to cpuids.txt and regenerate
unsigned char whoami(void);
#ifndef _WHO_H_
#define _WHO_H_

#define HOST 0x0
#define ME 0x0
#define YOU 0x0
#define DIRECT 0x0
#define NODE1 1
#define NODE2 2
#define NODE3 3
#define NODE4 4
#define ROUTING_POINTS 5

#endif
